CREATE FUNCTION DoubleExample( INTEGER)
    RETURNS INTEGER
    EXTERNAL NAME 'libdb2rustrtn.so!DoubleExample'
    NOT FENCED
    CALLED ON NULL INPUT
    NO SQL
    PARAMETER STYLE SQL
    LANGUAGE C
    THREADSAFE
    DETERMINISTIC
    NO DBINFO
    NO EXTERNAL ACTION@

